[package]
name = "lancelot"
description = "binary analysis framework for x32/x64 PE files"
license = "Apache-2.0"
version = "0.6.5"
authors = ["Willi Ballenthin <wilbal1087@gmail.com>"]
edition = "2018"
homepage = "https://github.com/williballenthin/lancelot"
repository = "https://github.com/williballenthin/lancelot"

[badges]
travis-ci = { repository = "https://github.com/williballenthin/lancelot", branch = "master" }

[dependencies]
log = "0.4"
goblin = { version = "0.4", features = ["std", "pe32"], default-features = false }
zydis = "3"
byteorder = "1"
bitflags = "1"
lazy_static = "1"
anyhow = "1"
thiserror = "1"
regex = "1"
smallvec = "1"
widestring = "0.4"
smol_str = "0.1"

fern = { version = "0.6", optional = true }
chrono = { version = "0.4", optional = true, features = ["std"], default-features = false }
bitvec = { version = "0.20", optional = true }

# https://github.com/myrrlyn/funty/issues/3#issuecomment-778629965
funty="=1.1.0"

lancelot-flirt = { path = "../flirt", version = "0.6.5", optional = true}

[dev-dependencies]
criterion = "0.3"
# while there is a newer unicorn-rs release (0.9.1)
# it doesn't build the underlying `unicorn` library transparently.
# so we use 0.8 that will do it for us.
#
# the upstream unicorn/next branch maintains rust bindings,
# but they're not published yet.
unicorn = "0.8.0"
dynasm = "1.0.1"
dynasmrt = "1.0.1"

[[bench]]
name = "emu"
harness = false

[features]
default = ["emu", "flirt"]
# The reason we do this is because doctests don't get cfg(test)
# See: https://github.com/rust-lang/cargo/issues/4669
test = ["chrono", "fern", "emu"]
flirt = ["lancelot-flirt"]
emu = ["bitvec"]
